### ISSUE TITLE
 A better 404 file needs to be crafted. 

### ISSUE THREAD

**Issue by lkurz** [HDFGroup/HDFGroup.github.io#291]
Fix links in existing 404 file.  Probably OK to just link back to main page.

A better looking 404 file needs to be crafted.  @loricooperhdf

**Comment by loricooperhdf** [comment]
https://github.com/HDFGroup/HDFGroup.github.io/pull/293

**Comment by lkurz** [comment]
Closing see https://github.com/HDFGroup/HDFGroup.github.io/pull/293
