### ISSUE TITLE
Documentation Typo and some questions on that documentation language and links

### ISSUE THREAD

**Issue by loricooperhdf** [HDFGroup/HDFGroup.github.io#292]
Under HDFView, latest is misspelled.

These are things that are questions--where I might have missed the discussion or forgot the discussion: 

- HDFView - Why do we need to keep the old link? 
- HDF5/JSON - I don't understand latest vs. full path. Is that temp? Will our users understand why there are two links?
- I guess I didn't see that we were hosting the h4toh5 docs (and some other docs) on zenodo.

**Comment by lkurz** [comment]
Lori,

Thanks.

Sorry typos do happen.  Broken links too.

We need to incorporate a link checker and linter into the development cycle and in the Jekyll workflows.

I am working on configuring a github codespace for the repo as an environment with some tools for working & testing code before creating PRs.

The extra links are temp.  Included in Gerd’s PR to demonstrate/test links.

Full path represents the “DOCS” location. Think of these as a kind of a shortend link or “PermaLink to structured storage location.  We do need to explore this concept further.  Jekyll has some concept of this, but so does CloudFront.

These extra links are not intended long term for users and should be removed from “support.hdfgroup.org”.

“Latest” links to a file on DOCS (currently lastest-docs.html) that redirects to the latest docs.  Ideally it shouldn’t need to be changed on support.hdfgroup.org every time there is a release.  The redirect file on DOCS would be changed at release time by the publishing workflows in the repos.

Gerd included the zenodo links in the PR .


From: Lori Cooper ***@***.***>
Reply-To: "HDFGroup/HDFGroup.github.io" ***@***.***>
Date: Friday, August 23, 2024 at 1:34 PM
To: "HDFGroup/HDFGroup.github.io" ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HDFGroup/HDFGroup.github.io] Documentation Typo and some questions on that documentation language and links (Issue #292)


Under HDFView, latest is misspelled.

These are things that are questions--where I might have missed the discussion or forgot the discussion:

  *   HDFView - Why do we need to keep the old link?
  *   HDF5/JSON - I don't understand latest vs. full path. Is that temp? Will our users understand why there are two links?
  *   I guess I didn't see that we were hosting the h4toh5 docs (and some other docs) on zenodo.

**Comment by lkurz** [comment]
Is there an Information Architect in the house?
We need to clarify our usage of zenodo.

**Comment by lkurz** [comment]
Links and misspellings referenced above have been removed.
And hopefully the questions answered.
