### ISSUE TITLE
Google analytics discussion

### ISSUE THREAD

**Issue by loricooperhdf** [HDFGroup/HDFGroup.github.io#301]
Looking to bounce this off @lkurz... I think we should re-use a GA property for the new support site. I'm leaning toward keeping the support.hdfgroup.org property with this new site (which will also be at that domain. Any objections?

**Comment by lkurz** [comment]
@loricooperhdf can you verify the code in the _includes/google-analytics.html file.
That must be an old code?  I don't see it at Analytics.

the new support site has more in common with Portal, but for which I don't see a GA property.
the old support site is substantially different so having a new tag wouldn't mix "plums and prunes".

But it's your decision.  What ever makes logging, monitoring and reporting 

an include statement for google-analytics.html will need to be added to the head section of the default layout 

SEO should be working now.  Are we using this?  Are we adding properties to markdown file frontmatter for seo puposes?

**Comment by loricooperhdf** [comment]
We never got it going on the github page/portal site. (See https://hdfgroup.atlassian.net/issues/IWIP-34) That code is correct for portal. Still thinking about what property I want it associated to.

**Comment by lkurz** [comment]
Any further thoughts on GA property?  It would be nice to see some analytics.
Based on our Teams chat re: portal maybe it best to create a new support property and keep activity segregated.

**Comment by lkurz** [comment]
New GA property created.  GA include added to default layout.
