### ISSUE TITLE
A couple missing doxygen files

### ISSUE THREAD

**Issue by lkurz** [HDFGroup/HDFGroup.github.io#310]
/releases/hdf5/v1_14/v1_14_4/documentation/doxygen/doxygen.png	
/releases/hdf5/v1_14/v1_14_4/documentation/doxygen/ftv2pnode.png

**Comment by byrnHDF** [comment]
Where is the requirement for them because there is a doxygen.svg file and the ftv2pnode.png file is not found  - not sure what requires that.

**Comment by lkurz** [comment]
<img width="921" alt="Screenshot 2024-08-30 at 8 31 57 AM" src="https://github.com/user-attachments/assets/2ee6b97c-a6cb-4b95-83f4-a7b57ce486ef">

<img width="568" alt="image" src="https://github.com/user-attachments/assets/adb2e06c-d879-4b23-bddd-c8a04aa746d6">

**Comment by lkurz** [comment]
> Could that be changed to use the svg file?

Yes but you need Graphviz and a few doxfile config settings.
Maybe we already have Graphviz available in our doxygen environment, but it seems a bit heavy for what appears to be seen in a footer and a navtree.

?

**Comment by lkurz** [comment]
CLOSING 

Let's move the missing doxygen.png issue to HDF5 repo.

the ftv2pnode.png is no longer getting a 404
It's not a huge deal for the doxygen output itself, 
but it floods the website logging with 404s cause it's on every footer of every doxygen page.

Doxygen builds apparently do give warnings for missing link targets, syntax.
@byrnHDF We should find a linter.
