### ISSUE TITLE
Typo on new_features_1_14 page

### ISSUE THREAD

**Issue by loricooperhdf** [HDFGroup/HDFGroup.github.io#322]
https://support.hdfgroup.org/documentation/hdf5-docs/release_specifics/new_features_1_14.html

> The new features in the HDF4 1.14 series include:

(Should be HDF5)

Also perhaps put the function names in backticks (`)

**Comment by lkurz** [comment]
Appears to be a simple typo fix. 

What's the deal about backticks?

**Comment by loricooperhdf** [comment]
It is very minor so I wanted to note it and maybe include it with other changes. Just in a hurry right this minute handling other release related changes.

Style for The HDF Group typically is to include functions in <code> or I guess in md, backticks. Recent example of two ways of notating code in Aleksandar's recent blog post: https://www.hdfgroup.org/2024/09/19/how-to-build-hdf5-library-and-h5py-in-a-conda-virtual-environment/
