### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by lkurz** [HDFGroup/HDFGroup.github.io#97]
Broken Link: https://www.hdfgroup.org/2023/11/release-of-hdf5-1-12-3-library-and-tools-newsletter-200/	
in https://portal.hdfgroup.org/downloads/hdf5/hdf5_1_12_3.html

**Comment by loricooperhdf** [comment]
After the excitement of Feb 20, exactly 20 blog posts were in the trash section on the www site. I restored those. This is fixed.
